### ISSUE TITLE
Call to a member function getDefaultVariation()

### ISSUE THREAD

**Issue by nalipaz** [agoradesign/commerce_product_set#1]
This is a great module.

I am having an issue with using this along with commerce_stock. It seems that when I attempt to load the Add to Cart form on a Product Set page I get:
```
The website encountered an unexpected error. Please try again later.
Error: Call to a member function getDefaultVariation() on null in commerce_stock_enforcement_form_alter() (line 39 of modules/contrib/commerce_stock/modules/enforcement/commerce_stock_enforcement.module).
```
Commerce_stock does do a form_alter there but the thing is it is looking for a property 'product' and it doesn't exist in the $form_state when this module is enabled.

**Comment by agoradesign** [comment]
Hi, I've commented on your issue at d.o here: https://www.drupal.org/project/commerce_stock/issues/3157889#comment-13739373

There's nothing else I can do for you here, as commerce_stock must simply check, if the order item is belonging to an product (variation) or not. Other modules run into the same problem, when stock is enabled, eg https://www.drupal.org/project/commerce_variation_cart_form/issues/3146653

**Comment by nalipaz** [comment]
Thanks for the quick response!

**Comment by nalipaz** [comment]
I did try out the suggested changes and they seemed to work correctly. I am testing some more and will post a patch at linked issue if it is working, thanks again!
